GitHub actions
NatLibFi/melinda-commons-js pull request #40
Opened 2022-09-01 13:20 UTC by ammsalme

2022-09-01 13:23 UTC, ammsalme commented
This waits for non-alpha-versions of:
"@natlibfi/marc-record": "^7.2.0-alpha.1",
"@natlibfi/marc-record-serializers": "^9.0.0-alpha.4",

2022-09-12 10:33 UTC, natlibfi-jonollil requested changes

2022-09-12 10:33 UTC, natlibfi-jonollil commented on package.json
> +		"@natlibfi/marc-record": "^7.2.0-alpha.1",
Can 7.2.0 be released before updating thins version to 12.0.4?

2022-09-12 10:33 UTC, natlibfi-jonollil commented on src/utils.js
> +    return value.length > 0 && value !== 'false' && value !== 'FALSE';
```
return value.length > 0 && !(/^(?:false)$/ui).test(value);
```
This way it covers even False and fALSE values

2022-10-03 08:27 UTC, natlibfi-jonollil approved these changes

2022-10-03 08:46 UTC, merged